// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/url/expand/{short}": {
            "get": {
                "parameters": [
                    {
                        "type": "string",
                        "description": "short",
                        "name": "short",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/url/hits/{short}": {
            "get": {
                "parameters": [
                    {
                        "type": "string",
                        "description": "short",
                        "name": "short",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/url/shorten": {
            "post": {
                "parameters": [
                    {
                        "description": "query params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ShortenURL.req"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "handler.ShortenURL.req": {
            "type": "object",
            "required": [
                "original_url"
            ],
            "properties": {
                "original_url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "https://mgmo.tech",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
